[package]
name = "golbat"
version = "0.2.5"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.24.0"

[lib]
crate-type = ["cdylib"]